const User = require('../models/User');
const Job = require('../models/Job');
const Payment = require('../models/Payment');
const WorkProgress = require('../models/WorkProgress');

class PastWorksService {
  /**
   * Automatically create a past work entry when a job is completed
   */
  static async createPastWorkFromJob(jobId) {
    try {
      // Get the job with all related data
      const job = await Job.findById(jobId)
        .populate('postedBy', 'name email')
        .populate('selectedContractor', 'name email');
      
      if (!job || !job.selectedContractor) {
        console.log('Job not found or no contractor selected:', jobId);
        return null;
      }

      // Check if job has required data for past work entry
      if (!job.rating || !job.review) {
        console.log('Job missing rating or review, skipping past work creation:', jobId);
        return null;
      }

      // Check if payment is completed
      const payment = await Payment.findOne({ 
        jobId: job._id, 
        status: 'completed' 
      });

      if (!payment) {
        console.log('Payment not completed yet, skipping past work creation:', jobId);
        return null;
      }

      // Check if past work entry already exists
      const existingEntry = await User.findOne({
        _id: job.selectedContractor._id,
        'profile.pastJobs.jobId': job._id
      });

      if (existingEntry) {
        console.log('Past work entry already exists for job:', jobId);
        return null;
      }

      // Get work progress to collect photos
      const workProgress = await WorkProgress.findOne({ jobId });
      let photos = [];
      
      if (workProgress && workProgress.weeklyProgress) {
        workProgress.weeklyProgress.forEach(progress => {
          if (progress.photos && progress.photos.length > 0) {
            photos = [...photos, ...progress.photos];
          }
        });
      }

      // Use job images as fallback if no progress photos
      if (photos.length === 0 && job.images && job.images.length > 0) {
        photos = job.images.slice(0, 3);
      }

      // Create past work entry
      const pastWorkEntry = {
        title: job.title,
        type: job.workType,
        description: job.description,
        budget: job.budget,
        date: job.updatedAt || new Date(),
        rating: job.rating || 0,
        photos: photos.slice(0, 10), // Limit to 10 photos
        landownerFeedback: job.review || '',
        landownerName: job.postedBy?.name || 'Unknown',
        landownerEmail: job.postedBy?.email || '',
        jobId: job._id,
        location: job.location,
        landSize: job.landSize,
        startDate: job.startDate,
        endDate: job.endDate,
        completionDate: job.updatedAt || new Date(),
        isAutoGenerated: true
      };

      // Add to contractor's past jobs
      const updatedContractor = await User.findByIdAndUpdate(
        job.selectedContractor._id,
        { 
          $push: { 'profile.pastJobs': pastWorkEntry },
          $inc: { 'profile.completedJobs': 1 }
        },
        { new: true }
      );

      // Update contractor statistics
      await this.updateContractorStatistics(job.selectedContractor._id);

      console.log('Past work entry created successfully for job:', jobId);
      return pastWorkEntry;
    } catch (error) {
      console.error('Error creating past work entry:', error);
      return null;
    }
  }

  /**
   * Update contractor statistics based on past works
   */
  static async updateContractorStatistics(contractorId) {
    try {
      const contractor = await User.findById(contractorId);
      if (!contractor) return;

      const pastWorks = contractor.profile?.pastJobs || [];
      
      // Calculate average rating
      const totalRating = pastWorks.reduce((sum, work) => sum + (work.rating || 0), 0);
      const averageRating = pastWorks.length > 0 ? totalRating / pastWorks.length : 0;
      
      // Calculate total earnings
      const totalEarnings = pastWorks.reduce((sum, work) => sum + (work.budget || 0), 0);
      
      // Update contractor profile
      await User.findByIdAndUpdate(contractorId, {
        $set: {
          'profile.averageRating': Math.round(averageRating * 10) / 10,
          'profile.totalEarnings': totalEarnings,
          'profile.completedJobs': pastWorks.length
        }
      });

      console.log(`Updated statistics for contractor ${contractor.name}: ${pastWorks.length} works, ${averageRating.toFixed(1)}⭐ avg, $${totalEarnings.toLocaleString()} total`);
    } catch (error) {
      console.error('Error updating contractor statistics:', error);
    }
  }

  /**
   * Get comprehensive past works data for a contractor
   */
  static async getContractorPastWorks(contractorId) {
    try {
      const contractor = await User.findById(contractorId);
      if (!contractor) return [];

      const pastWorks = contractor.profile?.pastJobs || [];
      
      // Sort by completion date (newest first)
      return pastWorks.sort((a, b) => new Date(b.completionDate || b.date) - new Date(a.completionDate || a.date));
    } catch (error) {
      console.error('Error getting contractor past works:', error);
      return [];
    }
  }

  /**
   * Add a manual past work entry
   */
  static async addManualPastWork(contractorId, pastWorkData) {
    try {
      const pastWorkEntry = {
        ...pastWorkData,
        date: new Date(pastWorkData.date),
        isAutoGenerated: false
      };

      const updatedContractor = await User.findByIdAndUpdate(
        contractorId,
        { $push: { 'profile.pastJobs': pastWorkEntry } },
        { new: true }
      );

      // Update statistics
      await this.updateContractorStatistics(contractorId);

      return updatedContractor.profile.pastJobs[updatedContractor.profile.pastJobs.length - 1];
    } catch (error) {
      console.error('Error adding manual past work:', error);
      throw error;
    }
  }

  /**
   * Update a past work entry
   */
  static async updatePastWork(contractorId, workId, updateData) {
    try {
      const updateFields = {};
      Object.keys(updateData).forEach(key => {
        if (updateData[key] !== undefined) {
          updateFields[`profile.pastJobs.$.${key}`] = updateData[key];
        }
      });

      const updatedContractor = await User.findOneAndUpdate(
        { 
          _id: contractorId,
          'profile.pastJobs._id': workId 
        },
        { $set: updateFields },
        { new: true }
      );

      if (!updatedContractor) {
        throw new Error('Past work not found');
      }

      // Update statistics
      await this.updateContractorStatistics(contractorId);

      return updatedContractor.profile.pastJobs.find(work => work._id.toString() === workId);
    } catch (error) {
      console.error('Error updating past work:', error);
      throw error;
    }
  }

  /**
   * Delete a past work entry
   */
  static async deletePastWork(contractorId, workId) {
    try {
      const updatedContractor = await User.findByIdAndUpdate(
        contractorId,
        { $pull: { 'profile.pastJobs': { _id: workId } } },
        { new: true }
      );

      if (!updatedContractor) {
        throw new Error('Contractor not found');
      }

      // Update statistics
      await this.updateContractorStatistics(contractorId);

      return true;
    } catch (error) {
      console.error('Error deleting past work:', error);
      throw error;
    }
  }

  /**
   * Get past works statistics for dashboard
   */
  static async getPastWorksStats(contractorId) {
    try {
      const contractor = await User.findById(contractorId);
      if (!contractor) return null;

      const pastWorks = contractor.profile?.pastJobs || [];
      
      const stats = {
        totalWorks: pastWorks.length,
        averageRating: 0,
        totalEarnings: 0,
        recentWorks: 0,
        autoGenerated: 0,
        manualEntries: 0
      };

      if (pastWorks.length > 0) {
        const totalRating = pastWorks.reduce((sum, work) => sum + (work.rating || 0), 0);
        stats.averageRating = Math.round((totalRating / pastWorks.length) * 10) / 10;
        stats.totalEarnings = pastWorks.reduce((sum, work) => sum + (work.budget || 0), 0);
        
        // Count recent works (last 30 days)
        const thirtyDaysAgo = new Date();
        thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
        stats.recentWorks = pastWorks.filter(work => 
          new Date(work.completionDate || work.date) >= thirtyDaysAgo
        ).length;

        // Count auto-generated vs manual entries
        stats.autoGenerated = pastWorks.filter(work => work.isAutoGenerated).length;
        stats.manualEntries = pastWorks.filter(work => !work.isAutoGenerated).length;
      }

      return stats;
    } catch (error) {
      console.error('Error getting past works stats:', error);
      return null;
    }
  }
}

module.exports = PastWorksService; 